package main;

public class IMatBackendEngine {

    //TODO HÄR KAN ALLA LISTOR ÖVER ORDRAR FINNAS. HIT KALLAR MAN OM MAN BEHÖVER GETTA T.EX. VAROR ETC
    //TODO DENNA KLASSEN KAN KOMMUNICERA MED DEN EXTERNA BACKENDEN.
}
